name: CI
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --warning-mode all --stacktrace
      - name: Check directories
        run: tree
      - name: Upload .jar file
        uses: actions/upload-artifact@v2
        with:
          name: Fabric JAR
          path: fabric/build/libs/plasmovoice-fabric-1.19-1.3.jar
